source "https://rubygems.org"

gem 'paperclip'
gem 'compass'
gem 'shotgun',              '0.9'
gem 'thin',                 '1.6.2'
gem 'aws-sdk',              '1.42.0'
gem 'dotenv',               '2.1.0'
gem 'hobbit',               '0.6.1'
gem 'mail',                 '2.6.3'
gem 'mimemagic',            '0.3.1'
gem 'mysql2',               '0.4.5'
gem 'pry',                  '0.9.12.6'
gem 'rack',                 '1.6.4'
gem 'rack-parser',          '0.6.1'
gem 'rack-protection',      '1.5.3'
gem 'rake',                 '10.5.0'
gem 'rest-client',          '1.8.0'
gem 'ruby-saml',            '1.0.0'
gem 'rubyzip',              '1.2.0'
gem 'sequel',               '4.31.0'
gem 'sequel-paranoid',      '0.6.2'
gem 'rubocop',              '0.24.0'
